export const GET_BLOGS = 'GET_BLOGS';
export const GET_HOMEPAGE = 'GET_HOMEPAGE';
export const CAROUSEL_CURRENT_SLIDE = 'CAROUSEL_CURRENT_SLIDE';
export const USERS_ERROR = 'USERS_ERROR';
export const SORT_BY_BLOG_SUBJECT = 'SORT_BY_BLOG_SUBJECT';
export const CAROUSEL_HOVER_STATE = 'CAROUSEL_HOVER_STATE';
export const CAROUSEL_INTERVAL = 'CAROUSEL_INTERVAL';